### ISSUE TITLE
Bidirectional?

### ISSUE THREAD

**Issue by nyaaaaaaatalie** [russellmcc/oscm#1]
Are there any plans to make this bidirectional? My use case is remote mixing, our mixer takes midi CC in for fader values and I would like the values the mixer sends to be sent back to an iPad we use for remote mixing. I'm a bit of a stranger to JavaScript or else I would do this myself.

**Comment by russellmcc** [comment]
Thanks for the suggestion, and sorry for the late response!  Unfortunately, I won't have time to do this in the foreseeable future :(.  There are a few non-open source tools for this, like https://osculator.net if you have a mac.
